version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data.db:/data.db
    command: [ "ppgloader sqlite://data.db postgresql://metabase:metabase@localhost:5432/my_db" ]

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_HOST: host_for_metabase_site
    depends_on:
      - postgres

volumes:
  postgres-data:
